# Generated by Django 3.1.3 on 2021-01-04 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dorm_final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_quality', models.IntegerField()),
                ('neighborhood', models.IntegerField()),
                ('q1', models.BooleanField()),
                ('q2', models.BooleanField()),
                ('q3', models.BooleanField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dorm_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iq', models.IntegerField()),
                ('kids_in_family', models.IntegerField()),
                ('whats_number', models.IntegerField()),
                ('Friends_count', models.IntegerField()),
                ('q1', models.BooleanField()),
                ('q2', models.BooleanField()),
                ('q3', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('born', models.DateField()),
                ('course', models.IntegerField()),
                ('is_need_dorm', models.BooleanField()),
                ('city_of_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.cities')),
                ('dorm_final', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.dorm_final')),
                ('dorm_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.dorm_form')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
